@echo off
rem This file generated by Jython installer
rem Created on XXX by bloch
rem
rem set JAVA_HOME=c:\jdk1.3.0_05\jre
REM * R_LZ_COPYRIGHT_BEGIN ***************************************************
REM * Copyright 2001-2004 Laszlo Systems, Inc.  All Rights Reserved.         *
REM * Use is subject to license terms.                                       *
REM * R_LZ_COPYRIGHT_END *****************************************************

set ARGS=

:loop
if [%1] == [] goto end
        set ARGS=%ARGS% %1
        shift
        goto loop
:end



"%JAVA_HOME%\bin\java.exe" "-Dpython.home=C:\jython-2.1" -classpath "C:\jython-2.1\jython.jar;%CLASSPATH%" org.python.util.jython %ARGS%

