#! /bin/bash -f

# For the debug LFC, we don't compile with --debug, as that turns on
# undefined warnings and is very slow, but we do turn on nameFunctions,
# which makes 'inspect' much more useful, and define $debug=true, which 
# will conditionally compile in the debug aspects of LaszloLibrary

# * P_LZ_COPYRIGHT_BEGIN ******************************************************
# * Copyright 2001-2004 Laszlo Systems, Inc.  All Rights Reserved.            *
# * Use is subject to license terms.                                          *
# * P_LZ_COPYRIGHT_END ********************************************************

runtime=`sed -n -e '/compiler.runtime.default/s/.*=swf\(.*\)$/\1/p' < ../config/lps.properties`
options=
while [ $# -gt 0 ]; do
  case "$1" in 
   -o ) output=$2 ; shift 2 ;;
   --runtime=* ) runtime=${1#--runtime=swf} ; shift ;;
   * ) options="${options} $1"; shift ;;
  esac
done
${LPS_HOME}/WEB-INF/lps/server/sc/bin/lfcbuilder --option nameFunctions --option warnGlobalAssignments \
    '-D$debug=true' --incremental --runtime=swf${runtime} -o ${output:-LFC${runtime}-debug.lzl} \
    --default LaszloLibrary.as ${options}

