#! /bin/bash -f

# * P_LZ_COPYRIGHT_BEGIN ******************************************************
# * Copyright 2001-2008 Laszlo Systems, Inc.  All Rights Reserved.            *
# * Use is subject to license terms.                                          *
# * P_LZ_COPYRIGHT_END ********************************************************

runtime=`sed -n -e '/compiler.runtime.default/s/.*=\(.*\)$/\1/p' < ../config/lps.properties`
options=
while [ $# -gt 0 ]; do
  case "$1" in 
   -o ) output=$2 ; shift 2 ;;
   --runtime=* ) runtime=${1#--runtime=} ; shift ;;
   * ) options="${options} $1"; shift ;;
  esac
done
if [ "$runtime" == "dhtml" ]; then
    suffix="js"
fi
if [ "$runtime" == "swf9" ]; then
    options="${options} --option buildSharedLibrary=true"
    suffix="swc"
fi
ant -Dlfc.output=${output:-LFC${runtime#swf}-profile-debug.${suffix:-"lzl"}} -Dlfc.runtime=${runtime} -Dlfc.source=LaszloLibrary.lzs \
    -Dlfc.options="--profile --option nameFunctions --option warnGlobalAssignments \"-D\\\$debug=true\" ${options}" lfc


