#! /bin/bash -f
# * P_LZ_COPYRIGHT_BEGIN ******************************************************
# * Copyright 2001-2006 Laszlo Systems, Inc.  All Rights Reserved.            *
# * Use is subject to license terms.                                          *
# * P_LZ_COPYRIGHT_END ********************************************************
if [ "${OS}" == Windows_NT ];  then
    . ${LPS_HOME}\\WEB-INF\\lps\\server\\bin\\lzenv
else
    . ${LPS_HOME}/WEB-INF/lps/server/bin/lzenv
fi

"${JAVA_HOME}/bin/java" "-Dpython.home=$JYTHON_HOME" "-DLPS_HOME=$LPS_HOME" "-Djava.ext.dirs=${JAVAEXTDIRS}" org.python.util.jython $*
