#!/usr/bin/perl
#
# This script generates a test suite .xml file from the file all_lzx.xml
# that is generated by the build command "ant lzx-catalog"
#
use File::Basename;

$inputfile = @ARGV[0];
$today = `date`;
chop($today);
while ( <> )
{
	# test suites root element
	if ( $_ =~ /^<tests>/)
	{
		print "<!-- LPS Test suites -->\n";
		print "<!-- Generated from $inputfile -->\n";
		print "<!-- $today -->\n\n";
		print "<test-suites>\n";
	}
	elsif ( $_ =~ /<test src=/)
	{
		# make a test suite tag
		
		# get the test name
		@test = split(/"/);
		$testname = @test[1];
		# test directory is the directory part of the test path name
		$testdir = dirname($testname);
		$testdir =~ s?/??;
		@name = split(/\//, $testdir);
		# test name is the last part of the test directory name
		$testname = pop(@name);
		$testname = ucfirst $testname;
		$newdir = 1;
		for $dir ( @dirlist )
		{
			if ( $testdir eq $dir )
			{
				$newdir = 0;
			}
		}
		if ($newdir == 1)
		{
			@dirlist = (@dirlist, $testdir);
			print "    <suite name=\"$testname\"\n";
			print "           directory=\"$testdir\"\n";
			print "           test=\"lps\" />\n";
		}
	}
	# end of test suites element
	elsif ( $_ =~ /^<\/tests>/)
	{
		print "</test-suites>\n";
	}
}
